%YAML:1.0
Frame.camera_id: Exif.Image.Model
Frame.heading: Xmp.exif.REALM.Heading
Frame.latitude_tag: Exif.GPSInfo.GPSLatitude
Frame.latituderef_tag: Exif.GPSInfo.GPSLatitudeRef
Frame.longitude_tag: Exif.GPSInfo.GPSLongitude
Frame.longituderef_tag: Exif.GPSInfo.GPSLongitudeRef
Frame.altitude_tag: Exif.GPSInfo.GPSAltitude
